##
## EPITECH PROJECT, 2023
## MyPrintf
## File description:
## Builds MyPrintf
##

SRC     =	printf_main.c	\
			printf_utils.c	\
			printf_utils2.c	\
			printf_utils_e.c	\

OBJ     =       $(SRC:.c=.o)

all:	$(OBJ)
	mv $(OBJ) ../
